<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <OutputPath>../bin/</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <RootNamespace>Python.Test.CSharpApi</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="OpenTAP" Version="9.24.0" />
        <OpenTapPackageReference Include="Python" Version="3.1.0" />
        <AdditionalOpenTapPackage Include="PythonExamples" Version="3.1.0" />
        
        <!-- Uncomment one of these lines to get a test plan editor installed when you build. -->
        <!-- <OpenTapPackageReference Include="Editor"/> -->
        <!-- <OpenTapPackageReference Include="Editor X"/> -->
        <!-- <OpenTapPackageReference Include="TUI"/> -->
    </ItemGroup>
    
    <ItemGroup>
      <Reference Include="Microsoft.CSharp">
        <HintPath>..\bin\Dependencies\Microsoft.CSharp.4.0.4.0\Microsoft.CSharp.dll</HintPath>
      </Reference>
    </ItemGroup>
    <Target Name="AfterBuildPython" BeforeTargets="Build;PostBuildEvent">
        <Exec Command="./tap python search-path --add .. " WorkingDirectory="$(OutputPath)" />
        <!--<Exec Command="./tap python update-stubs - -cache-file cache-file - -output-folder ../Stubs " WorkingDirectory="$(OutputPath)" />-->
    </Target>
</Project>
